### ISSUE TITLE
Get Setup Key Not Working

### ISSUE THREAD

**Issue by pkrasam** [GridPlus/client#2]
**Get Setup Key Not Working** 
Stuck on step 3 - Get your setup key and save it - https://github.com/GridPlus/client
Any help is greatly appreciated.
![grid _get_setup_key](https://user-images.githubusercontent.com/4514654/26952601-8d0136b2-4ce9-11e7-93dc-9fc8c660ece8.png)

**Comment by alex-miller-0** [comment]
I think you said on twitter this was working. I was having an issue where it would only pop up the setup key window if I refreshed the page, but I thought I fixed it. If someone can replicate that bug, please let me know here.
